version: 2

node: &node
  working_directory: /tmp
  docker:
    - image: circleci/node:9.11.1

jobs:
  create_base_env:
    <<: *node
    steps:
      - attach_workspace:
          at: /tmp
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
            - dependencies
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "yarn.lock" }}
  
  test:
    <<: *node
    steps:
      - attach_workspace:
         at: /tmp
      - run:
        name: Lint the code
        command: yarn lint
      - run:
        name: Unit test
        command: yarn unit --ci
      - run:
        name: End to end test
        command: yarn e2e
      - persist_to_workspace:
          root: .
          paths:
              - "*"

  build:
    <<: *node
    steps:
      - attach_workspace:
          at: ./
      - run:
         name: Build the app
         command: yarn build
      - store_artifacts:
          path: ./dist

workflows:
  version: 2
  test_and_build:
    jobs:
      - create_base_env
      - test:
          requires:
            - create_base_env
      - build:
          requires:
            - create_base_env
