version: 2

node: &node
  docker:
    - image: circleci/node:9.11.1

jobs:
  create_base_env:
    <<: *node
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
            - dependencies
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: .
          paths:
            - "*"
  
  test:
    <<: *node
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Lint the code
          command: yarn lint
      - run:
          name: Unit test
          command: yarn unit --ci --testResultsProcessor="jest-junit"
      - run:
          name: End to end test
          command: yarn e2e
      - run:
          name: Export code coverage to Codecov
          command: yarn ccov
      - store_test_results:
          path: ./test/unit/coverage

  build:
    <<: *node
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build the app
          command: yarn build
      - store_artifacts:
          path: ./dist

  dockerize:
    machine: true
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          name: Connect to Docker Hub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Build the container
          command: docker build -t $DOCKER_IMAGE_NAME:$CIRCLE_SHA1 -f CI.Dockerfile .
      - run:
          name: Add latest tag
          command: docker tag $DOCKER_IMAGE_NAME:$CIRCLE_SHA1 $DOCKER_IMAGE_NAME:latest
      - run:
          name: Push to the Docker Hub registry
          command: docker push $DOCKER_IMAGE_NAME:$CIRCLE_SHA1 && docker push $DOCKER_IMAGE_NAME:latest

workflows:
  version: 2
  test_build_deploy:
    jobs:
      - create_base_env
      - test:
          requires:
            - create_base_env
      - build:
          requires:
            - create_base_env
      - dockerize:
          requires:
            - build
          environment:
            DOCKER_IMAGE_NAME: "socialementcompetents/hackafront"
          filters:
            branches:
              only:
                - master
