version: 2

node: &node
  docker:
    - image: circleci/node:9.11.1

jobs:
  create_base_env:
    <<: *node
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
            - dependencies
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: .
          paths:
            - "*"
  
  test:
    <<: *node
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Lint the code
          command: yarn lint
      - run:
          name: Unit test
          command: yarn unit --ci --testResultsProcessor="jest-junit"
      - run:
          name: End to end test
          command: yarn e2e
      - store_test_results:
          path: ./test/unit/coverage

  build:
    <<: *node
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build the app
          command: yarn build
      - store_artifacts:
          path: ./dist

workflows:
  version: 2
  test_and_build:
    jobs:
      - create_base_env
      - test:
          requires:
            - create_base_env
      - build:
          requires:
            - create_base_env
